### PR TITLE
Implemented optional locales filtering

### PR DESCRIPTION
**Pull request by aleb2000**
Implements #24. Makes filtering locales on decode optional.

### CODE REVIEW

**Comment by leb-kuchen** [comment]
What is the advantage of using an Option over an empty slice?

**Comment by aleb2000** [comment]
An empty slice will prevent any locale from being included which I assume was the intended behavior. A None option would do the opposite, no filtering is done (hence all locales will be included).

**Comment by wiiznokes** [comment]
I may be worth renaming `locales` arg to `locales_filter`. This will make clear that a None variant will filter nothing

**Review by mmstick — APPROVED** [review]

**Comment by mmstick** [comment]
Since this is a breaking change, I will bump the major version.

**Pull request merged**
